spring:
  # PostgreSQL
  datasource:
    url: jdbc:postgresql://localhost:5432/moba_db
    username: admin
    password: password

  # MongoDB - The URI is the most reliable way to pass auth in modern Spring
  mongodb:
    uri: mongodb://admin:password@localhost:27017/match_history?authSource=admin

  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      # 'update' is fine for dev, 'create-drop' is better for clean testing
      ddl-auto: update